[workspace]

[package]
name = "cw-storage-plus"
version = "0.16.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Enhanced storage engines"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-storage-plus"
homepage = "https://cosmwasm.com"

[package.metadata.docs.rs]
all-features = true # include macro feature when building docs

[features]
default = ["iterator"]
iterator = ["cosmwasm-std/iterator"]
macro = ["cw-storage-macro"]

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
cosmwasm-std = { version = "1.0", default-features = false }
schemars = "0.8.3"
serde = { version = "1.0", default-features = false, features = ["derive"] }
cw-storage-macro = { version = "0.16.0", optional = true, path = "macros" }

# We don't use the following dependencies directly. They're dependencies of our dependencies.
# We specify them to tighten their version requirements so that builds with `-Zminimal-versions` work.
# Once we bump `cosmwasm-*` deps to a version after `1.1.5`, we can remove these.
k256 = { version = "0.11.1", features = ["ecdsa"] }
thiserror = "1.0.13"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
rand = "0.8"

# We don't use the following dependencies directly. They're dependencies of our dependencies.
# We specify them to tighten their version requirements so that builds with `-Zminimal-versions` work.
# Once we bump `cosmwasm-*` deps to a version after `1.1.5`, we can remove these.
serde_json = "1.0.40"

[[bench]]
name = "main"
harness = false
